[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
AcceleratedDCTs = "16e42a1c-b1d1-5566-807a-fe3b9ee7f6e1"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
