name = "AcceleratedDCTs"
uuid = "16e42a1c-b1d1-5566-807a-fe3b9ee7f6e1"
version = "0.3.0"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AbstractFFTs = "1.5.0"
FFTW = "1.10"
KernelAbstractions = "0.9.39"
julia = "1.11"
