name = "AcceleratedDCTs"
uuid = "16e42a1c-b1d1-5566-807a-fe3b9ee7f6e1"
version = "0.4.0"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[weakdeps]
CUDA = "052768ef-659d-540b-9e2d-98f1ee1e9d52"

[extensions]
VkDCTExt = "CUDA"

[compat]
AbstractFFTs = "1.5.0"
FFTW = "1.10"
KernelAbstractions = "0.9.39"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
